### ISSUE TITLE
UB and Bad Practice

### ISSUE THREAD

**Issue by gek169** [BellRampion/Library#1]
Most of your functions have pre-existing versions in <string.h>, you should be aware of that.

1) All your functions which use `int` when processing strings as a length are using bad practice, you should use size_t (in the c89 standard) or at the very least "unsigned long" so as to guarantee it is at least 32 bit (size_t is optimal). For exceedingly long strings exceeding INT_MAX, undefined behavior occurs from signed integer overflow.
2) `i = (c -'0');` You're assigning to a presumed pre-existing variable in this macro.
3) your strcpy implementation always returns zero.
4) bgetline has an *assumed undocumented size* for the input array. You should take in a pointer, rather than an array, and you should take in a length.
5) this is valid syntax: `while(*(s++) = *(s2++));`

**Comment by BellRampion** [comment]
I do know most of them have existing versions. These are copied directly from K&R and sometimes take different parameters than the library versions. 
Thank you for bringing these to my attention! I'll fix those and close this.

**Comment by BellRampion** [comment]
Fixed, so closing this. Please let me know if I missed something!

**Comment by gek169** [comment]
Alright!
